export interface Region {
  name: string;
  countries: string[];
}

export const marketAreas: Region[] = [
  {
    name: "Market Area",
    countries: [
      "Afghanistan",
      "Albania",
      "Andorra",
      "Argentina",
      "Aruba",
      "Australia",
      "Austria",
      "Bahamas",
      "Bangladesh",
      "Belarus",
      "Belgium",
      "Belize",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Caribbean",
      "China",
      "Colombia",
      "Congo",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Estonia",
      "European",
      "Fiji",
      "Finland",
      "France",
      "Gambia",
      "Germany",
      "Gibraltar",
      "Greece",
      "Grenada",
      "Guadeloupe",
      "Guatemala",
      "Guernsey",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Italy",
      "Jamaica",
      "Japan",
      "Kiribati",
      "Kosovo",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Macedonia",
      "Malaysia",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mexico",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Myanmar",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "North Korea",
      "Norway",
      "Pakistan",
      "Palau",
      "Papua New Guinea",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "Saint Vincent and the Grenadines",
      "San Marino",
      "Saudi Arabia",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "South America",
      "South Korea",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Tonga",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States (USA)",
      "Uzbekistan",
      "Venezuela",
      "Vietnam",
      "Yemen",
    ],
  },
  {
    name: "Russia",
    countries: [
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Nizhny Novgorod",
      "Samara",
      "Omsk",
      "Kazan",
      "Chelyabinsk",
      "Rostov-on-Don",
      "Ufa",
      "Volgograd",
      "Perm",
      "Krasnoyarsk",
      "Voronezh",
      "Saratov",
      "Krasnodar",
      "Vladivostok",
      "Irkutsk",
      "Tyumen",
      "Khabarovsk",
      "Makhachkala",
      "Orenburg",
      "Arkhangelsk",
      "Sochi",
      "Murmansk",
      "Yakutsk",
    ],
  },
  {
    name: "Germany",
    countries: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Dortmund",
      "Essen",
      "Bremen",
      "Dresden",
      "Leipzig",
      "Hanover",
      "Nuremberg",
      "Duisburg",
      "Bochum",
      "Wuppertal",
      "Bonn",
      "Mannheim",
      "Karlsruhe",
      "Wiesbaden",
      "Augsburg",
      "Aachen",
      "Kiel",
      "Freiburg",
      "Rostock",
      "Heidelberg",
    ],
  },
  {
    name: "United Kingdom",
    countries: [
      "London",
      "Aberdeen",
      "Belfast",
      "Birmingham",
      "Bradford",
      "Brighton & Hove",
      "Bristol",
      "Cambridge",
      "Cardiff",
      "Coventry",
      "Derby",
      "Durham",
      "Edinburgh",
      "Glasgow",
      "Leeds",
      "Leicester",
      "Liverpool",
      "Manchester",
      "Newcastle upon Tyne",
      "Nottingham",
      "Oxford",
      "Sheffield",
    ],
  },
  {
    name: "France",
    countries: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Le Havre",
      "Toulon",
      "Dijon",
      "Rouen",
      "Versailles",
      "Calais",
    ],
  },
  {
    name: "Italy",
    countries: [
      "Rome",
      "Milan",
      "Naples",
      "Turin",
      "Florence",
      "Bologna",
      "Genoa",
      "Palermo",
      "Venice",
      "Verona",
      "Bari",
      "Catania",
      "Parma",
      "Modena",
    ],
  },
  {
    name: "Spain",
    countries: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Murcia",
      "Palma",
      "Bilbao",
      "Alicante",
      "Valladolid",
      "Vigo",
      "Granada",
      "Oviedo",
    ],
  },
  {
    name: "United States (USA)",
    countries: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "San Francisco",
      "Indianapolis",
      "Columbus",
      "Fort Worth",
      "Charlotte",
      "Detroit",
      "Seattle",
      "Denver",
      "Washington",
      "Boston",
      "Las Vegas",
      "Phoenix",
      "Portland",
      "Miami",
    ],
  },
  {
    name: "Canada",
    countries: [
      "Toronto",
      "Vancouver",
      "Montreal",
      "Calgary",
      "Ottawa",
      "Edmonton",
      "Winnipeg",
      "Halifax",
      "Hamilton",
      "Quebec City",
    ],
  },
  {
    name: "Australia",
    countries: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Canberra",
      "Newcastle",
      "Wollongong",
      "Hobart",
      "Darwin",
      "Geelong",
      "Townsville",
      "Cairns",
    ],
  },
  {
    name: "New Zealand",
    countries: [
      "Auckland",
      "Wellington",
      "Christchurch",
      "Hamilton",
      "Tauranga",
      "Dunedin",
      "Rotorua",
      "Palmerston North",
      "Invercargill",
    ],
  },
  {
    name: "Caribbean",
    countries: [
      "Saint Kitts and Nevis",
      "Antigua and Barbuda",
      "Dominica",
      "Barbados",
      "Saint Lucia",
      "Trinidad and Tobago",
      "Dominican Republic",
    ],
  },
  {
    name: "South America",
    countries: ["Suriname", "French Guiana"],
  },
  {
    name: "European",
    countries: [
      "Bratislava",
      "Belgrade",
      "Kyiv",
      "Istanbul",
      "Warsaw",
      "Amsterdam",
      "Lisbon",
      "Vienna",
      "Stockholm",
      "Athens",
      "Budapest",
      "Prague",
      "Brussels",
      "Bucharest",
      "Porto",
      "Minsk",
      "Sofia",
      "Donostia San Sebastian",
      "Copenhagen",
      "Reykjavik",
      "Oslo",
      "Helsinki",
      "Kharkiv",
      "Ljubljana",
      "Dublin",
      "Odesa",
    ],
  },
];
